import {chromium,webkit,expect} from "@playwright/test";
import {readFile,mkdir,writeFile} from "node:fs/promises";
import assert from "node:assert/strict";
const credentials=JSON.parse(await readFile(".local/qa-credentials.json","utf8"));
await mkdir(".local/qa",{recursive:true});
const summary=[];
for(const [engine,type] of [["chromium",chromium],["webkit",webkit]]){
 const browser=await type.launch({headless:true,...(engine==="chromium"?{args:["--no-sandbox"]}:{})});
 try{
  const context=await browser.newContext({viewport:{width:390,height:844},isMobile:true,hasTouch:true,deviceScaleFactor:1});
  const page=await context.newPage();const errors=[],historyRequests=[];
  page.on("pageerror",e=>errors.push(e.message));
  page.on("request",req=>{if(req.url().includes("/history"))historyRequests.push(req.url());});
  await page.goto("http://127.0.0.1:8782/");
  if(engine==="chromium"){
   await page.getByText("Открой личную ссылку первого входа, чтобы задать пароль.",{exact:true}).waitFor();
   await page.goto("http://127.0.0.1:8782/#setup="+credentials.setupToken);
  }
  await page.getByLabel(engine==="chromium"?"Придумай пароль":"Пароль",{exact:true}).fill(credentials.password);
  if(engine==="chromium")await page.getByLabel("Повтори пароль").fill(credentials.password);
  await page.getByRole("button",{name:engine==="chromium"?"Сохранить и войти":"Войти",exact:true}).click();
  await page.locator(".message").last().waitFor();
  assert.equal(await page.locator(".message").count(),20);
  assert.ok(historyRequests.length<=2,"History must not be downloaded in full");
  assert.equal(await page.locator('input[type=text]').count(),0,"Login has no username field");
  assert.ok(await page.locator(".chat-pane").isVisible());
  assert.equal(await page.locator(".support-pane").isVisible(),false);
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
  assert.equal(overflow,false,"No horizontal page overflow");
  await page.getByLabel("Модель Codex",{exact:true}).selectOption("qa-text");
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Режим Codex"]').disabled);
  await page.getByLabel("Режим Codex",{exact:true}).selectOption("plan");
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Уровень размышления"]').disabled);
  await page.getByLabel("Уровень размышления",{exact:true}).selectOption("high");
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Модель Codex"]').disabled);
  await page.reload();
  await page.getByLabel("Модель Codex",{exact:true}).waitFor();
  await expect(page.getByLabel("Модель Codex",{exact:true})).toHaveValue("qa-text");
  await expect(page.getByLabel("Режим Codex",{exact:true})).toHaveValue("plan");
  await expect(page.getByLabel("Уровень размышления",{exact:true})).toHaveValue("high");
  await page.getByLabel("Модель Codex",{exact:true}).selectOption("qa-model");
  await page.waitForFunction(()=>!document.querySelector('[aria-label="Модель Codex"]').disabled);
  await page.getByLabel("Выбрать файлы или изображения",{exact:true}).setInputFiles({name:"mobile-note.txt",mimeType:"text/plain",buffer:Buffer.from("Attachment round trip from "+engine)});
  await page.getByRole("button",{name:"Удалить mobile-note.txt",exact:true}).waitFor();
  await page.getByRole("button",{name:"Удалить mobile-note.txt",exact:true}).click();
  await page.getByRole("button",{name:"Удалить mobile-note.txt",exact:true}).waitFor({state:"detached"});
  await page.getByLabel("Выбрать файлы или изображения",{exact:true}).setInputFiles({name:"mobile-note.txt",mimeType:"text/plain",buffer:Buffer.from("Attachment round trip from "+engine)});
  await page.getByRole("button",{name:"Удалить mobile-note.txt",exact:true}).waitFor();
  await page.screenshot({path:".local/qa/"+engine+"-mobile-chat.png"});
  await page.locator(".chat-scroll").evaluate(el=>el.scrollTop=0);
  await page.getByRole("button",{name:"Загрузить предыдущие",exact:true}).click();
  await page.waitForFunction(()=>document.querySelectorAll(".message").length===40);
  const top=await page.locator(".chat-scroll").evaluate(el=>el.scrollTop);
  assert.ok(top>0,"Prepending older messages keeps the reading position");
  await page.getByRole("textbox",{name:"Сообщение Codex"}).fill("Черновик, который нужно сохранить");
  await page.getByRole("navigation",{name:"Разделы рабочего пространства"}).getByRole("button",{name:/Результаты/}).click();
  assert.equal(await page.locator(".chat-pane").isVisible(),false);
  assert.ok(await page.locator(".results-pane").isVisible());
  await page.getByRole("button",{name:"К сообщению",exact:true}).last().click();
  await page.locator(".history-loader").getByText("Фрагмент диалога",{exact:true}).waitFor();
  assert.equal(await page.locator(".message").count(),20);
  await page.getByRole("button",{name:"К последним сообщениям",exact:true}).click();
  await page.locator(".chat-scroll").evaluate(el=>el.scrollTop=el.scrollHeight);
  assert.equal(await page.getByRole("textbox",{name:"Сообщение Codex"}).inputValue(),"Черновик, который нужно сохранить");
  await page.getByRole("textbox",{name:"Сообщение Codex"}).fill("Проверка отправки и подтверждения");
  await page.getByRole("button",{name:"Отправить сообщение",exact:true}).click();
  await page.getByRole("button",{name:"Разрешить",exact:true}).waitFor();
  await page.reload();
  await page.getByRole("button",{name:"Отклонить",exact:true}).waitFor();
  assert.ok(await page.locator(".message").getByRole("link",{name:/mobile-note.txt/}).last().isVisible());
  await page.getByRole("button",{name:"Отклонить",exact:true}).click();
  await page.getByText("Готово. Проверка интерфейса подтверждений завершена.",{exact:true}).last().waitFor();
  await page.getByRole("navigation",{name:"Разделы рабочего пространства"}).getByRole("button",{name:"Remote",exact:true}).click();
  await page.getByRole("button",{name:"Подключиться",exact:true}).click();
  await page.getByText("Подключено",{exact:true}).waitFor({timeout:25000});
  await page.getByRole("button",{name:"Снимок",exact:true}).click();
  await page.getByText("Снимок сохранён в результатах",{exact:true}).waitFor();
  await page.getByRole("navigation",{name:"Разделы рабочего пространства"}).getByRole("button",{name:/Результаты/}).click();
  await page.getByRole("button",{name:"Открыть снимок",exact:true}).first().click();
  await page.getByRole("dialog",{name:"Просмотр снимка"}).waitFor();
  const colors=await page.locator(".image-viewer img").evaluate(async img=>{
   await img.decode();const c=document.createElement("canvas");c.width=32;c.height=32;const x=c.getContext("2d");x.drawImage(img,0,0,32,32);
   const d=x.getImageData(0,0,32,32).data;const colors=new Set();for(let n=0;n<d.length;n+=4)colors.add([d[n],d[n+1],d[n+2],d[n+3]].join(","));return colors.size;
  });
  assert.ok(colors>8,"Remote screenshot must contain a rendered desktop, not an empty frame");
  await page.getByRole("button",{name:"Закрыть снимок",exact:true}).click();
  await page.getByRole("button",{name:"Настройки",exact:true}).last().click();
  await page.getByLabel("Зелёный терминал",{exact:false}).check();
  await page.getByRole("button",{name:"Закрыть настройки",exact:true}).click();
  await page.getByRole("navigation",{name:"Разделы рабочего пространства"}).getByRole("button",{name:"Чат",exact:true}).click();
  await page.screenshot({path:".local/qa/"+engine+"-mobile-crt.png"});
  await page.setViewportSize({width:1366,height:1024});
  await page.screenshot({path:".local/qa/"+engine+"-ipad.png"});
  assert.ok(await page.locator(".desktop-nav").isVisible());
  assert.ok(await page.locator(".chat-pane").isVisible());
  assert.ok(await page.locator(".results-pane").isVisible());
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  assert.deepEqual(errors,[],"No browser errors");
  summary.push({engine,mobileHistory:true,historyButtonPreservesPosition:true,passwordEnrollment:engine==="chromium",approvalsSurviveReload:true,modelModeEffort:true,attachments:true,remoteDesktop:true,screenshotSaved:true,tablet:true,consoleErrors:errors});
  await context.close();
 }finally{await browser.close();}
}
await writeFile(".local/qa/summary.json",JSON.stringify(summary,null,2));
console.log(JSON.stringify(summary,null,2));
